"""Agregar categoria a los productos

Revision ID: 2abb70ac9e3d
Revises: 7d339b597fcd
Create Date: 2025-02-27 14:13:40.050670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2abb70ac9e3d'
down_revision = '7d339b597fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
